#!/usr/bin/env python3
"""Generate docs/overhaul/qa/RUNTIME_TEST_MATRIX.md from tools/overhaul/qa/runtime_cases.py + the recorded results in
docs/overhaul/qa/runtime_test_matrix.json (the evidence ledger). Never invents results: a (case, revision) with no recorded
result is NOT RUN. A PASS/FAIL requires actual result, tester, date and evidence reference (checked by validate_runtime_matrix.py).

    python3 tools/overhaul/qa/build_runtime_matrix.py          # (re)write the ledger skeleton if missing + the markdown
    python3 tools/overhaul/qa/build_runtime_matrix.py --check  # ledger/markdown are current
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from runtime_cases import CASES, GROUPS_REQUIRED, REVISIONS  # noqa: E402

ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
LEDGER = os.path.join(ROOT, "docs/overhaul/qa/runtime_test_matrix.json")
MD = os.path.join(ROOT, "docs/overhaul/qa/RUNTIME_TEST_MATRIX.md")
EMPTY = {"actual": "", "result": "NOT RUN", "tester": "", "date": "", "evidence": ""}


def load_ledger():
    if os.path.exists(LEDGER):
        with open(LEDGER, encoding="utf-8") as f:
            return json.load(f)
    return {"schema": "pokeplatinum-overhaul/d7-runtime-matrix-ledger/v1",
            "rule": "Only a human/emulator execution may set PASS or FAIL; each requires actual, tester, date, evidence.", "results": {}}


def render(led):
    res = led["results"]
    counts = {"PASS": 0, "FAIL": 0, "NOT RUN": 0}
    for c in CASES:
        for rev in REVISIONS:
            counts[res.get(f"{c[0]}|{rev}", EMPTY)["result"]] += 1
    out = ["# Runtime Test Matrix (D7)", "",
           "Generated by `python3 tools/overhaul/qa/build_runtime_matrix.py` from `tools/overhaul/qa/runtime_cases.py` (cases) and "
           "`docs/overhaul/qa/runtime_test_matrix.json` (evidence ledger). **Do not hand-edit results here** — record them in the ledger.", "",
           f"**State: {counts['PASS']} PASS / {counts['FAIL']} FAIL / {counts['NOT RUN']} NOT RUN** across {len(CASES)} cases × {len(REVISIONS)} revisions "
           f"({len(CASES) * len(REVISIONS)} runs).", "",
           "No emulator or hardware was available to the author of this matrix, so every run is **NOT RUN**. This is expected and is not a pass; "
           "static validation (`MASTER_VALIDATION_REPORT.md`) is not a substitute. A case may be marked PASS only by executing its steps on that "
           "revision and recording actual result, tester, date and evidence (screenshot/log/save-state reference).", "",
           "**Known open runtime failure (D8, user-reported; not a PASS/FAIL ledger entry because the revision was not recorded):** after confirming a Mystery Egg both "
           "screens went black indefinitely with music still playing, and the eggs rendered tiny in the briefcase. Fixes are in source (RELEASE_BLOCKERS C-1/C-2) but "
           "**unverified at runtime**: OP-01, OP-02, OP-03, OP-09, OP-10 and OP-11 must be re-run on both revisions and stay NOT RUN until then.", "",
           "Result vocabulary: `PASS`, `FAIL`, `NOT RUN`. Revisions: " + ", ".join(REVISIONS) + ".", "",
           "## Index", ""]
    for g in GROUPS_REQUIRED:
        ids = [c[0] for c in CASES if c[1] == g]
        out.append(f"* **{g}** ({len(ids)}): {', '.join(ids)}")
    out.append("")
    cur = None
    for cid, grp, title, setup, steps, expected, auth in CASES:
        if grp != cur:
            cur = grp
            out += [f"## {grp}", ""]
        out += [f"### {cid} — {title}", "", f"* **Setup / save requirement:** {setup}", f"* **Steps:** {steps}", f"* **Expected:** {expected}",
                f"* **Authority:** {auth}", "", "| Revision | Actual result | Result | Tester / date | Evidence |", "|---|---|---|---|---|"]
        for rev in REVISIONS:
            r = res.get(f"{cid}|{rev}", EMPTY)
            out.append(f"| {rev} | {r['actual'] or '—'} | **{r['result']}** | {(r['tester'] + ' / ' + r['date']) if r['tester'] else '—'} | {r['evidence'] or '—'} |")
        out.append("")
    return "\n".join(out), counts


def main():
    led = load_ledger()
    md, _ = render(led)
    if "--check" in sys.argv:
        cur = open(MD, encoding="utf-8").read() if os.path.exists(MD) else ""
        if cur != md:
            print("RUNTIME_TEST_MATRIX.md is stale; run build_runtime_matrix.py")
            return 1
        return 0
    with open(LEDGER, "w", encoding="utf-8") as f:
        json.dump(led, f, indent=1, sort_keys=True)
        f.write("\n")
    with open(MD, "w", encoding="utf-8") as f:
        f.write(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
