#!/usr/bin/env python3
"""D7 Phase 6: run the locked D2 progression profiles against final source and write the QA report.

Integrity gates (fail the run): live boss aces == locked aces, no unresolved species, deterministic reruns.
Tolerance results are REPORTED, not gated: the model is a calibration approximation (see report), so a flag is a
runtime-QA item, never grounds for blanket trainer rescaling.
"""
from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tools/overhaul/economy"))
import simulate_progression as sp  # noqa: E402

REPORT = "docs/overhaul/qa/PROGRESSION_SIMULATION_REPORT.md"
JSON_OUT = "docs/overhaul/qa/progression_simulation_qa.json"
# Locked D2 targets (EXP_ECONOMY_SPEC.md s.3), expressed as (min, max) of party-average minus boss ace.
TOL = {"direct": (-4.0, None), "normal": (-3.0, 2.0), "completionist": (None, 2.0)}


def run(include_story):
    tables, cache = sp.load_tables(), {}
    seg, boss, aces, missing = sp.collect_segments(cache, include_story)
    wild = sp.wild_per_segment(cache)
    spec = [b[2] for b in sp.BOSSES]
    out = {"aces_live": aces, "aces_spec": spec, "unresolved": sorted(missing), "profiles": {}}
    for prof in sp.PROFILES:
        tw = sp.simulate(prof, True, tables, seg, boss, wild, spec)
        van = sp.simulate(prof, False, tables, seg, boss, wild, spec)
        lo, hi = TOL[prof]
        rows = []
        for t, v in zip(tw, van):
            d = round(t["avg"] - t["ace"], 1)
            ok = (lo is None or d >= lo) and (hi is None or d <= hi)
            rows.append({"boss": t["boss"], "ace": t["ace"], "avg": t["avg"], "median": t["median"], "max": t["max"],
                         "delta_vs_ace": d, "vanilla_delta_vs_ace": round(v["avg"] - v["ace"], 1), "in_tolerance": ok})
        out["profiles"][prof] = {"rows": rows, "out_of_tolerance": [r["boss"] for r in rows if not r["in_tolerance"]]}
    return out


def table(res):
    lines = []
    for prof, r in res["profiles"].items():
        lo, hi = TOL[prof]
        lines.append(f"\n**{prof}** — target Δ(avg−ace) in [{lo if lo is not None else '−∞'}, {hi if hi is not None else '+∞'}]; "
                     f"out of tolerance: {len(r['out_of_tolerance'])}/13\n")
        lines.append("| Boss | Ace | Party avg | Median | Δ vs ace | Vanilla-EXP Δ | In tol. |\n|---|---|---|---|---|---|---|")
        for x in r["rows"]:
            lines.append(f"| {x['boss']} | {x['ace']} | {x['avg']} | {x['median']} | {x['delta_vs_ace']:+} | "
                         f"{x['vanilla_delta_vs_ace']:+} | {'yes' if x['in_tolerance'] else '**no**'} |")
    return "\n".join(lines)


def main() -> int:
    a, b = run(False), run(True)
    errs = []
    for tag, r in (("default", a), ("story", b)):
        if r["aces_live"] != r["aces_spec"]:
            errs.append(f"{tag}: live boss aces {r['aces_live']} != locked {r['aces_spec']}")
        if r["unresolved"]:
            errs.append(f"{tag}: unresolved species {r['unresolved']}")
    if run(False) != a:
        errs.append("simulation is not deterministic")
    summary = {"model_default": {p: v["out_of_tolerance"] for p, v in a["profiles"].items()},
               "model_with_story_trainers": {p: v["out_of_tolerance"] for p, v in b["profiles"].items()},
               "integrity_errors": errs}
    with open(os.path.join(ROOT, JSON_OUT), "w", encoding="utf-8") as f:
        json.dump({"summary": summary, "default": a, "with_story_trainers": b}, f, indent=1, sort_keys=True)
        f.write("\n")
    md = f"""# Progression Simulation Report (D7 Phase 6)

Generated by `python3 tools/overhaul/qa/progression_report.py` against **final** source (trainer levels from
`res/trainers/data`, final conserved 60/40 team-wide EXP via `tools/overhaul/economy/exp_model.py`, final wild manifest).
Machine-readable copy: `docs/overhaul/qa/progression_simulation_qa.json`.

**Integrity:** live boss aces == locked aces {a['aces_spec']}: {'PASS' if a['aces_live'] == a['aces_spec'] else 'FAIL'};
unresolved species: {len(a['unresolved'])}; deterministic: {'PASS' if not any('deterministic' in e for e in errs) else 'FAIL'}.

**Status: NOT A VERIFICATION.** This is the locked D2 *calibration model*, not human play. It is reported against the locked
tolerances (direct ≥ −4 vs ace; normal −3…+2; completionist ≤ +2), but a model flag is a runtime-QA item, not proof of a
source defect, and no trainer level was changed (no blanket rescaling).

## Diagnosis of the drift

1. **Default model omits 92 mandatory story trainers** (Rival, Galactic grunts/commanders, Lucas/Dawn, Cyrus) from the EXP supply
   (`ORDINARY_EXCLUDE`). The rotating-party average is therefore far too low from Byron onward (normal: −4…−13 at Byron–Cynthia).
2. **Same shortfall under vanilla EXP in the same model** (rightmost column): the gap is a model-coverage effect, not caused by the
   conserved team-wide EXP change (which shifts the curve by only ~+1…+3 levels, as designed).
3. Adding the story fights (`--include-story-trainers`, new optional flag, default OFF so the committed D2 output is unchanged) shrinks the
   normal-profile deficit (worst Cynthia −12.8 → −7.2; Byron −3.5 → +1.7) but **26/39 profile×boss cells remain outside tolerance**
   (second table), so the model still does not demonstrate the locked targets.
4. Residual: early overage for completionist/normal (Roark–Candice, up to +4…+8.6 completionist) and a normal-explorer E4/Cynthia
   deficit (−3.5…−7.2) remain model-flagged. The completionist profile fights 100% of optional trainers plus 24 wild KOs per
   segment, which is grind-adjacent by construction. These are **calibration-review items for the human campaign**, recorded in
   `RELEASE_BLOCKERS.md` (section B), not auto-corrected: the Gym/E4/Cynthia aces are exact locked values, and the spec forbids
   speculative balance edits. No owning-subsystem source defect was proven, so **no source change was made**.

## Default model (committed D2 behavior)
{table(a)}

## Model + mandatory story trainers (`--include-story-trainers`)
{table(b)}
"""
    with open(os.path.join(ROOT, REPORT), "w", encoding="utf-8") as f:
        f.write(md)
    for e in errs:
        print("FAIL", e)
    n = lambda r: sum(len(v) for v in r.values())
    print(f"progression: integrity {'FAIL' if errs else 'OK'}; out-of-tolerance boss-profiles default={n(summary['model_default'])}/39, "
          f"with story trainers={n(summary['model_with_story_trainers'])}/39 (reported, not gated)")
    return 1 if errs else 0


if __name__ == "__main__":
    sys.exit(main())
