"""Mandatory D7 runtime cases (data only). Source of truth for docs/overhaul/qa/RUNTIME_TEST_MATRIX.md and runtime_test_matrix.json.
(id, group, title, setup/save requirement, steps, expected, authority). Every case runs once per supported revision (Rev 0 and Rev 1).
Expected results quote the locked manifests; nothing here is evidence - results live in runtime_test_matrix.json."""

CASES = [
 # ---------------- MOVES (spec s5) ----------------
 ("MV-01", "MOVES", "Magnet Volley hits exactly 3 times at equal 25 BP", "Probopass (or any holder) knowing Magnet Volley vs a high-HP, non-Steel-resistant target; no Substitute",
  "1) Use Magnet Volley; 2) count hit messages and per-hit damage; 3) repeat vs a target with Focus Sash / low HP to confirm early-faint stop.",
  "'Hit 3 time(s)!'; three damage rolls drawn from the same 25-BP formula (no Triple Kick-style 25/50/75 escalation); stops only when target faints or Substitute breaks.", "created_moves_manifest.json implementation_invariants.magnet_volley"),
 ("MV-02", "MOVES", "Resonant Slash is a sound move (Soundproof)", "Resonant Slash user vs Soundproof target (Exploud/Voltorb/Electrode)",
  "Use Resonant Slash on the Soundproof target; then on a Substitute-protected target.", "No damage / Soundproof message on the Soundproof target; sound-move Substitute bypass behaves like Hyper Voice; normal damage otherwise (60 BP, Bug, high crit).", "created_moves_manifest.json implementation_invariants.sound_registry"),
 ("MV-03", "MOVES", "Star Jab is a punching move (Iron Fist)", "Infernape/Chimchar line (Iron Fist) with Star Jab vs identical non-Iron-Fist user",
  "Compare damage rolls with and without Iron Fist (same level/stats via two Pokémon or ability swap by evolution).", "Iron Fist boosts Star Jab like other punching moves (x1.2); 20% flinch still present; 65 BP Bug physical.", "created_moves_manifest.json implementation_invariants.punch_registry"),
 ("MV-04", "MOVES", "Razor Wind is a single-turn high-crit move", "Any Razor Wind user vs a standard target", "Use Razor Wind; observe turn count; compare crit rate over >=30 uses.", "Executes the same turn (no charge turn, no 'whipped up a whirlwind' charge); elevated crit ratio; description text no longer says two-turn.", "c1_move_changes_manifest.json (Razor Wind effect reassignment)"),
 ("MV-05", "MOVES", "Defog removes hazards and screens", "Opposing side with Spikes/Toxic Spikes/Stealth Rock and Reflect/Light Screen; Defog user", "Use Defog; check both sides' conditions and evasion drop.", "Hazards/screens removed as per C2 locked spec; evasion lowered; fails/behaves per spec when nothing to remove.", "docs/overhaul/tm_hm/TM_HM_SPEC.md"),
 ("MV-06", "MOVES", "All 22 created moves usable: text, animation, no crash", "Pokémon (or debug-assisted party) knowing each of IDs 468-489 in turn",
  "Select each move from the battle menu and from the Summary/Move screens; observe name, description, PP, animation, message.", "Correct name/type/class/PP; description matches behavior; animation plays; no freeze; Solar Petal makes contact (D7 fix) and charges unless harsh sun.", "created_moves_manifest.json"),
 ("MV-07", "MOVES", "C1 representative edits (Fury Cutter, Bind/Wrap/Fire Spin/Whirlpool/Sand Tomb/Clamp, Magma Storm keep)", "Summary screen / Move Tutor list; one battle each for a trapping move",
  "Inspect BP/Acc/PP on the Summary screen for 8 sampled edited moves; use a trapping move once.", "Values equal the C1 manifest (e.g. Bind 30/90/20, Fire Spin 35/90/15, Clamp 35/90/10, Magma Storm 120/70/5); trapping duration unchanged.", "c1_move_changes_manifest.json"),
 ("MV-08", "MOVES", "Reusable TMs consume no item", "Bag with TMs; any compatible Pokémon", "Teach a TM, check Bag quantity; teach same TM to a second Pokémon.", "TM remains in the Bag after use (reusable); HM/TM compat per C3H masks.", "c2_mechanics_manifest.json"),
 ("MV-09", "MOVES", "HM battle effects match locked spec", "Party with all HM users", "In battle use each HM move (Cut/Fly/Surf/Strength/Defog/Rock Smash/Waterfall/Rock Climb) and compare with the C2 spec table.", "Each HM move's battle effect equals the locked spec; field use unchanged.", "tm_hm/TM_HM_SPEC.md; c2_mechanics_manifest.json"),
 ("MV-10", "MOVES", "TM21 Air Slash / TM78 Power Gem recipients", "Sample 6 recipients and 4 non-recipients each", "Open TM compat in Bag/learn screen.", "Recipient/non-recipient results match the 49/27-species masks; Frustration/Captivate masks did not leak.", "tm_compat_manifest.json"),
 ("MV-11", "MOVES", "Retyped / role-repair family spot-check", "Summary screens of every retyped family (one per family)", "Check type, ability slots, stats, learnset highlights against the C3 snapshot.", "Matches the C3H species snapshot (incl. Banette, Torkoal, Seviper final corrections; Glalie Ice/Steel).", "c3_species_provenance.json; ledgers"),
 # ---------------- EVOLUTION ----------------
 ("EV-01", "EVOLUTION", "Happiny -> Chansey at Lv20 in daytime, no Oval Stone", "Happiny Lv19; daytime and nighttime clocks", "Level to 20 at night (no evolution), then in daytime.", "Evolves only in daytime, no held item needed.", "evolution_manifest.json"),
 ("EV-02", "EVOLUTION", "Night evolutions Gligar/Sneasel Lv38", "Gligar and Sneasel Lv37; night clock", "Level to 38 in day then in night.", "Evolve into Gliscor/Weavile only at night, no item.", "evolution_manifest.json"),
 ("EV-03", "EVOLUTION", "Stat-branch evolutions (Tyrogue, Poliwhirl, Slowpoke line, Clamperl)", "One Pokémon per branch with controlled stats", "Level to the threshold with each stat relationship (>, =, <).", "Each branch yields the locked target (e.g. Poliwhirl: SpA>Atk -> Politoed; Atk>=SpA -> Poliwrath).", "evolution_manifest.json"),
 ("EV-04", "EVOLUTION", "Move-known evolutions", "Aipom/Lickitung/Tangela/Yanma/Piloswine/Mime Jr./Bonsly with and without the move", "Level up with/without the required move; teach via level/tutor/egg path.", "Evolves only while the move is known; every required move is obtainable.", "evolution_graph.json"),
 ("EV-05", "EVOLUTION", "Lv36 final evolutions without trade (Kadabra/Machoke/Graveler/Haunter)", "Each at Lv35", "Level to 36.", "Evolve into Alakazam/Machamp/Golem/Gengar with no trade or item.", "evolution/EVOLUTION_SPEC.md"),
 ("EV-06", "EVOLUTION", "Porygon line Lv30 / Lv45; Dusclops Lv45; Onix/Scyther/Seadra/Electabuzz/Magmar/Rhydon levels", "One of each at level-1", "Level to the threshold.", "Correct evolution at the locked level; no item required.", "evolution_manifest.json"),
 ("EV-07", "EVOLUTION", "Evolution stones from the Veilstone vendor", "Money >= 2100 per stone; evolution candidates (Eevee, Pikachu, Gloom, Staryu, Kirlia, Snorunt...)", "Buy each stone at Veilstone Dept. Store 2F; use on candidates (incl. male/female stone cases).", "All 9 stones sold at the listed price; evolutions succeed; stone stock is unlimited.", "economy_manifest.json evolution_stone_shop"),
 ("EV-08", "EVOLUTION", "Location evolutions (Magnetic field / Moss Rock / Ice Rock) and friendship/Beauty", "Magneton/Nosepass/Eevee/Feebas", "Level up at the native locations; raise friendship/Beauty.", "Magnezone/Probopass/Leafeon/Glaceon/Milotic evolve at the native locations/conditions.", "evolution_graph.json"),
 ("EV-09", "EVOLUTION", "Mantyke with Remoraid, Shedinja/Ninjask", "Mantyke + Remoraid in party; Nincada with free slot + Poké Ball", "Level up under each condition.", "Mantine requires Remoraid in party; Ninjask evolves, Shedinja created when slot and ball available.", "evolution_graph.json"),
 # ---------------- EXP / ECONOMY ----------------
 ("EX-01", "EXP/ECONOMY", "Team-wide EXP conservation with 1, 3 and 6 eligible Pokémon", "Parties of 1/3/6 eligible members, same level", "Defeat the same wild Pokémon with 1 participant each time; record EXP gained by every member.", "Total EXP distributed equals the vanilla raw pool (60/40 conserved), not multiplied by party size.", "economy/EXP_ECONOMY_SPEC.md; exp_model.py"),
 ("EX-02", "EXP/ECONOMY", "Participant-only EVs", "Party of 3: 1 participant, 2 team-share-only", "Defeat a known-EV species; check Summary EVs.", "Only participants gain EVs; team-share-only recipients gain EXP but no EVs.", "EXP_ECONOMY_SPEC.md"),
 ("EX-03", "EXP/ECONOMY", "Exp. Share priority and fainted/Lv100/Egg exclusion", "Exp. Share holder, a Lv100 member, an Egg, a fainted member", "Defeat a foe; compare shares.", "Priority per spec; Lv100/Egg/fainted get nothing and are excluded from the denominator; pool is redistributed.", "EXP_ECONOMY_SPEC.md"),
 ("EX-04", "EXP/ECONOMY", "Trainer / traded / Lucky Egg modifiers", "Traded-origin Pokémon, Lucky Egg holder, trainer battle", "Compare EXP vs controlled baseline.", "1.5x trainer, 1.5x traded (1.7x foreign), 1.5x Lucky Egg as modeled.", "exp_model.py"),
 ("EX-05", "EXP/ECONOMY", "Shop inventory and prices", "Visit the town marts, the Veilstone Dept. Store and the Frontier shop", "Compare stock/prices with the economy manifest; verify no unexpected Poké Ball price changes.", "Prices/stock equal economy_manifest.json and pokeball_shop_manifest.json.", "economy_manifest.json"),
 ("EX-06", "EXP/ECONOMY", "Free Move Reminder", "Pokémon with relearnable moves; Pastoria Move Reminder", "Talk to the Reminder.", "No Heart Scale/cost required; access still gated by reaching Pastoria.", "EXP_ECONOMY_SPEC.md"),
 ("EX-07", "EXP/ECONOMY", "Shard tutors cost half", "Shards; the shard move tutors", "Check costs for several moves.", "Costs are exactly half the vanilla shard price.", "economy_manifest.json tutors"),
 ("EX-08", "EXP/ECONOMY", "Postgame Rare Candy source gating", "Before and after Hall of Fame", "Check shops/BP exchange for Rare Candy.", "No pre-E4 shop sells it; postgame source is available at the locked price.", "economy_manifest.json rare_candy_postgame"),
 # ---------------- CAPTURE ----------------
 ("CP-01", "CAPTURE", "Quick Ball: turn one vs later", "Fresh wild encounter; ~200 attempts per condition or forced-state debug", "Throw on turn 1 vs turn 2+.", "Turn one modifier 5.0x; later 1.0x.", "pokeball_manifest.json"),
 ("CP-02", "CAPTURE", "Timer Ball progression", "Same, throw on turns 1, 5, 10, 20", "Compare catch rates.", "Modifier 1.0 + 0.3/turn capped at 4.0.", "pokeball_manifest.json"),
 ("CP-03", "CAPTURE", "Repeat Ball caught vs uncaught", "Species already caught vs new", "Throw each.", "3.5x on caught species, 1.0x otherwise.", "pokeball_manifest.json"),
 ("CP-04", "CAPTURE", "Dusk Ball cave/night", "Cave daytime, outdoors night, outdoors day", "Throw in each.", "3.0x in cave or at night; 1.0x otherwise.", "pokeball_manifest.json"),
 ("CP-05", "CAPTURE", "Net Ball Water/Bug", "Water-type, Bug-type, other target", "Throw each.", "3.5x vs Water/Bug; 1.0x otherwise.", "pokeball_manifest.json"),
 ("CP-06", "CAPTURE", "Dive Ball water-terrain logic", "Surf/fishing encounter vs land", "Throw each.", "4.0x on water terrain, 1.0x on land.", "pokeball_manifest.json"),
 ("CP-07", "CAPTURE", "Heal Ball multiplier + post-capture healing", "Damaged/statused target", "Capture with Heal Ball.", "1.5x; caught Pokémon fully healed.", "pokeball_manifest.json"),
 ("CP-08", "CAPTURE", "Nest Ball level-ratio behavior", "Low-level target vs high-level user", "Throw with various level gaps.", "Level-ratio modifier per manifest.", "pokeball_manifest.json"),
 ("CP-09", "CAPTURE", "Standard Great/Ultra baseline and availability", "Marts at each progression stage", "Check when Great/Ultra/Dive balls appear; throw baselines.", "Great 1.5x, Ultra 2x baseline; shop availability per pokeball_shop_manifest.json.", "pokeball_shop_manifest.json"),
 # ---------------- BREEDING ----------------
 ("BR-01", "BREEDING", "Everstone: 100% nature inheritance", "Parent holding Everstone x 20 eggs", "Hatch 20 eggs.", "Nature always from the Everstone holder.", "breeding_rules.json"),
 ("BR-02", "BREEDING", "Four inherited IV stats", "Two high-IV parents x 20 eggs", "Hatch and inspect IVs.", "Exactly four distinct IV stats inherited from parents.", "breeding_rules.json"),
 ("BR-03", "BREEDING", "Power items force inheritance", "Parent with each Power item", "Hatch several eggs per item.", "The Power item's stat is always inherited from that parent.", "breeding_rules.json"),
 ("BR-04", "BREEDING", "Ability inheritance", "Parents with slot-2/hidden-slot abilities", "Hatch many eggs.", "Per locked D4 ability inheritance probabilities.", "BREEDING_SPEC.md"),
 ("BR-05", "BREEDING", "Either-parent egg moves", "Male-only egg-move holder and female parent", "Breed and inspect move set.", "Egg moves inherited from either parent as locked.", "egg_move_changes.json"),
 ("BR-06", "BREEDING", "All nine no-incense babies", "Adults of each baby line, no incense", "Breed each.", "Baby species hatches without incense for all nine.", "breeding_rules.json; egg_group_changes.json"),
 ("BR-07", "BREEDING", "128-step egg checks, hatch speed, minimum 5 cycles", "Fresh egg; step counter", "Walk and count egg-generation checks and hatch cycles.", "Checks every 128 steps; half hatch cycles with minimum 5.", "hatch_cycle_changes.json"),
 ("BR-08", "BREEDING", "Flame Body / Magma Armor hatch speed", "Lead with ability", "Hatch with/without.", "Hatch speed bonus per spec.", "BREEDING_SPEC.md"),
 ("BR-09", "BREEDING", "Masuda regression", "Foreign-language parents (if possible)", "Hatch many eggs.", "Shiny odds behavior unchanged from vanilla unless manifested.", "BREEDING_SPEC.md"),
 ("BR-10", "BREEDING", "Manaphy + Ditto -> Phione and special cases", "Manaphy, Ditto", "Breed.", "Phione egg produced; special-species cases per spec.", "BREEDING_SPEC.md"),
 # ---------------- TRAINERS ----------------
 ("TR-01", "TRAINERS", "Gym 1 Roark", "Fresh-save progress to Oreburgh", "Beat Roark; record party levels/EXP.", "Locked team/levels (ace 14); no held items in Gym 1; fair vs 2-3 member party.", "trainer_overhaul_manifest.json"),
 ("TR-02", "TRAINERS", "Gym 2 Gardenia", "Progress", "Battle.", "Locked team (ace 22).", "trainer_overhaul_manifest.json"),
 ("TR-03", "TRAINERS", "Gym 3 Fantina", "Progress", "Battle.", "Locked team (ace 27).", "trainer_overhaul_manifest.json"),
 ("TR-04", "TRAINERS", "Gym 4 Maylene", "Progress", "Battle.", "Locked team (ace 32).", "trainer_overhaul_manifest.json"),
 ("TR-05", "TRAINERS", "Gym 5 Crasher Wake", "Progress", "Battle.", "Locked team (ace 37).", "trainer_overhaul_manifest.json"),
 ("TR-06", "TRAINERS", "Gym 6 Byron", "Progress", "Battle.", "Locked team (ace 41).", "trainer_overhaul_manifest.json"),
 ("TR-07", "TRAINERS", "Gym 7 Candice", "Progress", "Battle.", "Locked team (ace 44).", "trainer_overhaul_manifest.json"),
 ("TR-08", "TRAINERS", "Gym 8 Volkner", "Progress", "Battle.", "Locked team (ace 50).", "trainer_overhaul_manifest.json"),
 ("TR-09", "TRAINERS", "Rival early encounters for each starter branch", "Each starter choice", "Battle.", "Starter-branch team per locked table.", "trainer_overhaul_manifest.json"),
 ("TR-10", "TRAINERS", "Rival mid-game battles", "Progress", "Battle.", "Locked team/levels per branch.", "trainer_overhaul_manifest.json"),
 ("TR-11", "TRAINERS", "Rival League-stage battle", "Pre-League", "Battle.", "Locked team/levels.", "trainer_overhaul_manifest.json"),
 ("TR-12", "TRAINERS", "Galactic: Mars, Jupiter, Saturn, Cyrus", "Story progress", "Battle each.", "Locked teams; commanders distinct from grunts; Cyrus main-story peak before E4.", "trainer_overhaul_manifest.json"),
 ("TR-13", "TRAINERS", "Elite Four: Aaron, Bertha, Flint, Lucian", "Pre-League", "Battle each.", "Locked teams (aces 53/55/57/59).", "trainer_overhaul_manifest.json"),
 ("TR-14", "TRAINERS", "Champion Cynthia", "After E4", "Battle.", "Locked team (ace 62); main-story peak.", "trainer_overhaul_manifest.json"),
 ("TR-15", "TRAINERS", "Representative rematches (Gym, E4, Cynthia, Fight Area)", "After Hall of Fame", "Rematch several.", "Stronger National Dex teams per rematch tables.", "trainer_overhaul_manifest.json; rematch_access.json"),
 ("TR-16", "TRAINERS", "Ordinary-trainer sampling per band", "One route trainer per band", "Battle.", "Below boss difficulty; species available in same/earlier band.", "trainer_overhaul_manifest.json"),
 # ---------------- EVENTS ----------------
 ("EVT-01", "EVENTS", "Native retry: Uxie/Azelf defeat, flee, blackout then re-enter", "Pre-HoF save at lakes", "Defeat/flee/blackout, return.", "Encounter returns until captured; capture flag only set on capture.", "native_legendary_events.json"),
 ("EVT-02", "EVENTS", "Roamers Mesprit/Cresselia faint/reset", "Roamer active", "Faint roamer; reset.", "Roamer respawns after reset script; captured state unique.", "native_legendary_events.json"),
 ("EVT-03", "EVENTS", "Giratina (incl. Turnback Cave fallback), Dialga, Palkia, Heatran", "Story progress", "Defeat/flee each.", "Retry-safe; Dialga/Palkia states set only on capture.", "native_legendary_events.json"),
 ("EVT-04", "EVENTS", "Darkrai (Member Card -> Newmoon Island)", "After HoF, National Dex, Lunar Wing sequence", "Obtain Member Card, ferry, battle.", "Event available without distribution gate; retry-safe.", "native_legendary_events.json"),
 ("EVT-05", "EVENTS", "Shaymin (Oak's Letter, Seaside Cave...)", "After HoF + National Dex", "Receive the letter on Route 224 and follow the quest.", "Event proceeds without distribution gate; retry-safe.", "native_legendary_events.json"),
 ("EVT-06", "EVENTS", "Arceus prerequisite (#001-#492 caught) and Azure Flute", "Dex missing exactly one species vs complete", "Talk to Rowan at Veilstone B1F.", "Flute only after all #001-#492 caught; Arceus battle retry-safe.", "native_legendary_events.json"),
 ("EVT-07", "EVENTS", "Manaphy Egg gift incl. full party", "After HoF + child sequence; full party", "Talk to Sailor Eldritch with full vs free-slot party.", "Egg given only with a free slot, nothing lost; gift flag set once.", "native_legendary_events.json"),
 ("EVT-08", "EVENTS", "Regirock/Regice/Registeel braille puzzles and Regigigas", "After HoF; three Regis in party", "Solve puzzles; battle Regigigas.", "Regis catchable without event; Regigigas requires the three Regis.", "native_legendary_events.json"),
 ("EVT-09", "EVENTS", "Rotom forms and Secret Key", "Old Chateau; Rotom's room", "Capture Rotom; use appliances.", "Secret Key given; all five forms obtainable; no distribution gate.", "native_legendary_events.json rotom"),
 ("EVT-10", "EVENTS", "Legacy habitats (14 legends, post-HoF 1%/2%)", "After HoF; each listed map/method", "Encounter-sample each habitat (debug-assisted rate counting allowed).", "Rolls ~2% (Rare) / ~1% (Apex); ordinary table unaffected on miss.", "legacy_legendary_encounters.json"),
 ("EVT-11", "EVENTS", "Mythical statics Mew/Celebi/Jirachi/Deoxys", "After HoF", "Trigger each static; defeat/flee then retry.", "Retry-safe; captured flag set only on capture.", "mythical_statics.json"),
 # ---------------- ENCOUNTERS / ACQUISITION ----------------
 ("WD-01", "ENCOUNTERS", "One representative map per availability band E0-P1", "Progress per band", "Sample each map's table.", "Species/rates per wild_encounters.json; >=5% required sources.", "wild_encounters.json"),
 ("WD-02", "ENCOUNTERS", "Land/cave/Surf/Old/Good/Super Rod", "Rods obtained", "Sample each method.", "Method sources match manifest; no inaccessible method source.", "wild_encounters.json method_gates"),
 ("WD-03", "ENCOUNTERS", "Day/night fallback", "Clock set day/night", "Sample.", "Time-of-day alters abundance, never sole availability.", "wild_encounters.json"),
 ("WD-04", "ENCOUNTERS", "Honey/Marsh/Radar/swarm/Garden bonus behavior", "Each system", "Sample.", "Bonus systems behave per spec and are never the sole source.", "AVAILABILITY_ARCHITECTURE.md"),
 ("WD-05", "ENCOUNTERS", "Former dual-slot families", "No GBA cart", "Sample each former dual-slot family.", "Obtainable without Slot-2.", "availability validator"),
 ("WD-06", "ENCOUNTERS", "Special acquisitions: starters, fossils, Spiritomb, Tyrogue, Happiny, Eevee, Porygon, Riolu, Castform, Feebas", "Progress per family", "Perform each acquisition.", "Each obtainable, retry-safe, in one save.", "special_acquisitions.json"),
 # ---------------- POSTGAME / FRONTIER ----------------
 ("PG-01", "POSTGAME", "Battle Tower ordinary set (2x BP)", "After HoF", "Complete one set; record BP.", "Payout is exactly the doubled value.", "frontier_rewards.json"),
 ("PG-02", "POSTGAME", "Battle Factory ordinary set (2x BP)", "After HoF", "Complete one set.", "Doubled BP.", "frontier_rewards.json"),
 ("PG-03", "POSTGAME", "Battle Castle ordinary set (2x BP, CP untouched)", "After HoF", "Complete one set.", "Doubled BP; Castle Points unchanged.", "frontier_rewards.json"),
 ("PG-04", "POSTGAME", "Battle Hall ordinary set (2x BP + record keeper)", "After HoF", "Complete one set.", "Doubled BP incl. record keeper.", "frontier_rewards.json"),
 ("PG-05", "POSTGAME", "Battle Arcade ordinary set (2x BP + roulette)", "After HoF", "Complete one set.", "Doubled BP incl. roulette.", "frontier_rewards.json"),
 ("PG-06", "POSTGAME", "Silver Print reward path", "Silver Print on one facility", "Claim.", "+BP per manifest, one-time; all-Silver bonus (+50 BP, PP Max).", "print_rewards.json"),
 ("PG-07", "POSTGAME", "Gold Print / Brain reward path", "Gold Print", "Beat Brain; claim.", "Per-facility +30 BP; all-Gold +100 BP + Master Ball; one-time.", "print_rewards.json"),
 ("PG-08", "POSTGAME", "Battleground proprietor reshuffle without calendar wait", "Fight Area Battleground", "Reshuffle twice same day.", "Allowed without waiting.", "rematch_access.json"),
 ("PG-09", "POSTGAME", "Daily Rival rematch", "Survival Area", "Battle on weekday, again next day.", "Available daily; team per trainer authority.", "rematch_access.json"),
 ("PG-10", "POSTGAME", "Print rewards full-bag retry", "Bag full", "Claim; free a slot; claim again.", "Reward not lost; retry succeeds; no duplicate.", "print_rewards.json"),
 ("PG-11", "POSTGAME", "Frontier TM BP prices", "BP shop", "Compare price list.", "Locked TM BP prices exact; non-TM prices unchanged.", "frontier_shop_prices.json"),
 # ---------------- FIELD / SOFTLOCK (spec s14) ----------------
 ("FD-01", "FIELD", "Badge/HM/field-move progression and story warps", "Fresh save", "Play main story gates in order.", "No impossible flag order; no dead-end.", "FINAL_INTEGRATION_QA_SPEC.md s14"),
 ("FD-02", "FIELD", "National Dex gate and event item flags", "After HoF", "Receive National Dex; item flags.", "Flags set once; dependent events unlock.", "FINAL_INTEGRATION_QA_SPEC.md s14"),
 ("FD-03", "FIELD", "One-time gifts with full party / full Bag", "Full party, full Bag", "Trigger each gift.", "No gift lost; retry possible.", "FINAL_INTEGRATION_QA_SPEC.md s14"),
 ("FD-04", "FIELD", "Day Care and marts", "Day Care Pokémon", "Deposit/retrieve; shop.", "Normal operation under Breeding 2.0.", "FINAL_INTEGRATION_QA_SPEC.md s14"),
 ("FD-05", "FIELD", "Distortion World and postgame route unblock", "Story", "Traverse.", "No softlock; routes unblock after HoF.", "FINAL_INTEGRATION_QA_SPEC.md s14"),
 # ---------------- CAMPAIGN / COMPLETION ----------------
 ("CG-01", "CAMPAIGN", "Fresh-save full campaign start -> Hall of Fame (5-6 rotating team, no progression cheats)", "New save, each revision for at least a representative segment; full run on one revision", "Play; fill FULL_CAMPAIGN_REPORT.md at every gate.", "Party medians within target bands; no softlock; no required grinding.", "FINAL_INTEGRATION_QA_SPEC.md s15"),
 ("CG-02", "CAMPAIGN", "493 completion run on one save", "Postgame save", "Acquire all species via real paths; record in POKEDEX_493_COMPLETION_REPORT.md.", "All 493 obtained without direct Pokédex-bit injection.", "FINAL_INTEGRATION_QA_SPEC.md s16"),
 # ---------------- SAVE ----------------
 ("SV-01", "SAVE", "Fresh overhaul save create/save/reload", "New game", "Save, reset, load.", "Loads intact.", "FINAL_INTEGRATION_QA_SPEC.md s17"),
 ("SV-02", "SAVE", "Vanilla US save imported by matching revision", "Matching vanilla Rev 0 and Rev 1 saves", "Load in the overhaul build; play a few battles; save.", "Loads and plays; no corruption (round-trip back to vanilla not supported).", "FINAL_INTEGRATION_QA_SPEC.md s17"),
 ("SV-03", "SAVE", "Save/reload with created-move Pokémon", "Pokémon knowing IDs 468-489", "Save, reload, open summaries.", "Moves intact.", "FINAL_INTEGRATION_QA_SPEC.md s17"),
 ("SV-04", "SAVE", "Save/reload after new event flags", "After D5 events", "Save, reload, check events.", "Flags persist.", "FINAL_INTEGRATION_QA_SPEC.md s17"),
 ("SV-05", "SAVE", "Save/reload after Frontier/breeding activity", "After a facility set and eggs", "Save, reload.", "Records/eggs intact.", "FINAL_INTEGRATION_QA_SPEC.md s17"),
]
GROUPS_REQUIRED = ["MOVES", "EVOLUTION", "EXP/ECONOMY", "CAPTURE", "BREEDING", "TRAINERS", "EVENTS", "ENCOUNTERS", "POSTGAME", "FIELD", "CAMPAIGN", "SAVE"]
REVISIONS = ["US Rev 0", "US Rev 1"]
