"""Hand-reviewed movesets for important trainers whose moves the locked spec leaves unspecified ("fill").

Per trainer: moves per party slot in party order.  Every move is checked against the current legal pool by
the validator; created moves appear only where the spec names them or the species is a manifest recipient.
"""
M = lambda *a: list(a)  # noqa: E731

CURATED = {
    # --- Team Galactic -------------------------------------------------------------------------------------------
    "commander_mars_valley_windworks": [M("BITE", "LEECH_LIFE", "TOXIC", "SUPERSONIC"),
                                         M("FAKE_OUT", "FAINT_ATTACK", "SCRATCH", "HYPNOSIS")],
    "commander_jupiter_team_galactic_eterna_building": [M("BITE", "WING_ATTACK", "LEECH_LIFE", "TOXIC"),
                                                        M("SLASH", "POISON_GAS", "SCREECH", "SMOKE_SCREEN")],
    "commander_saturn_valor_cavern": [M("AIR_CUTTER", "BITE", "POISON_FANG", "CONFUSE_RAY"),
                                       M("GYRO_BALL", "EXTRASENSORY", "SHADOW_BALL", "IRON_DEFENSE"),
                                       M("AURA_BURST", "POISON_JAB", "REVENGE", "FAINT_ATTACK")],
    "commander_mars_lake_verity": [M("AIR_CUTTER", "BITE", "POISON_FANG", "CONFUSE_RAY"),
                                    M("GYRO_BALL", "EXTRASENSORY", "IRON_DEFENSE", "CONFUSE_RAY"),
                                    M("SLASH", "FAINT_ATTACK", "HYPNOSIS", "FAKE_OUT")],
    "commander_saturn_galactic_hq": [M("CROSS_POISON", "AIR_SLASH", "BITE", "CONFUSE_RAY"),
                                      M("GYRO_BALL", "EXTRASENSORY", "SHADOW_BALL", "CONFUSE_RAY"),
                                      M("AURA_BURST", "POISON_JAB", "BRICK_BREAK", "FAINT_ATTACK")],
    "galactic_boss_cyrus_galactic_hq": [M("NIGHT_SLASH", "ICE_PUNCH", "QUICK_ATTACK", "SCREECH"),
                                         M("CROSS_POISON", "AIR_SLASH", "BITE", "CONFUSE_RAY"),
                                         M("FLAMETHROWER", "DARK_PULSE", "WILL_O_WISP", "SLUDGE_BOMB"),
                                         M("NIGHT_SLASH", "SUCKER_PUNCH", "AIR_SLASH", "HEAT_WAVE")],
    "galactic_boss_cyrus_distortion_world": [M("FLAMETHROWER", "DARK_PULSE", "WILL_O_WISP", "THUNDER_FANG"),
                                              M("CROSS_POISON", "AIR_SLASH", "TOXIC", "CONFUSE_RAY"),
                                              M("WATERFALL", "ICE_FANG", "EARTHQUAKE", "DRAGON_DANCE"),
                                              M("NIGHT_SLASH", "AIR_SLASH", "HEAT_WAVE", "PSYCHIC"),
                                              M("NIGHT_SLASH", "ICE_PUNCH", "X_SCISSOR", "AERIAL_ACE")],
    "commander_mars_spear_pillar": [M("GYRO_BALL", "EXTRASENSORY", "LIGHT_SCREEN", "CONFUSE_RAY"),
                                     M("CROSS_POISON", "AIR_SLASH", "BITE", "CONFUSE_RAY"),
                                     M("SLASH", "SHADOW_CLAW", "AERIAL_ACE", "HYPNOSIS")],
    "commander_jupiter_spear_pillar": [M("GYRO_BALL", "EXTRASENSORY", "ROCK_SLIDE", "REFLECT"),
                                        M("SLUDGE_BOMB", "AIR_SLASH", "GIGA_DRAIN", "MEAN_LOOK"),
                                        M("NIGHT_SLASH", "POISON_JAB", "FLAMETHROWER", "SMOKE_SCREEN")],
    "commander_mars_stark_mountain": [M("GYRO_BALL", "EXTRASENSORY", "LIGHT_SCREEN", "CONFUSE_RAY"),
                                       M("CROSS_POISON", "AIR_SLASH", "BITE", "CONFUSE_RAY"),
                                       M("SLASH", "SHADOW_CLAW", "AERIAL_ACE", "HYPNOSIS")],
    "commander_jupiter_stark_mountain": [M("GYRO_BALL", "EXTRASENSORY", "ROCK_SLIDE", "REFLECT"),
                                          M("SLUDGE_BOMB", "AIR_SLASH", "GIGA_DRAIN", "MEAN_LOOK"),
                                          M("NIGHT_SLASH", "POISON_JAB", "FLAMETHROWER", "SMOKE_SCREEN")],
    # --- Elite Four / Champion ----------------------------------------------------------------------------------
    "elite_four_aaron": [M("AIR_SLASH", "SIGNAL_BEAM", "U_TURN", "DOUBLE_TEAM"),
                          M("IRON_HEAD", "X_SCISSOR", "NIGHT_SLASH", "QUICK_ATTACK"),
                          M("ATTACK_ORDER", "DEFEND_ORDER", "HEAL_ORDER", "POWER_GEM"),
                          M("CLOSE_COMBAT", "STONE_EDGE", "NIGHT_SLASH", "AERIAL_ACE"),
                          M("X_SCISSOR", "CROSS_POISON", "ICE_FANG", "AERIAL_ACE")],
    "elite_four_bertha": [M("EARTH_POWER", "AQUA_TAIL", "ZEN_HEADBUTT", "SANDSTORM"),
                           M("EARTHQUAKE", "STONE_EDGE", "CRUNCH", "YAWN"),
                           M("EARTHQUAKE", "FIRE_PUNCH", "THUNDER_PUNCH", "SANDSTORM"),
                           M("EARTHQUAKE", "ICE_FANG", "FIRE_FANG", "THUNDER_FANG"),
                           M("EARTHQUAKE", "STONE_EDGE", "AVALANCHE", "SUPERPOWER")],
    "elite_four_flint": [M("FLAMETHROWER", "SLUDGE_BOMB", "DARK_PULSE", "SUNNY_DAY"),
                          M("FLARE_BLITZ", "SOLAR_BEAM", "BOUNCE", "SUNNY_DAY"),
                          M("OVERHEAT", "QUICK_ATTACK", "WILL_O_WISP", "SHADOW_BALL"),
                          M("FLARE_BLITZ", "THUNDER_PUNCH", "MACH_PUNCH", "EARTHQUAKE"),
                          M("FLAMETHROWER", "THUNDERBOLT", "SOLAR_BEAM", "FOCUS_BLAST")],
    "elite_four_lucian": [M("PSYCHIC", "THUNDERBOLT", "REFLECT", "LIGHT_SCREEN"),
                           M("PSYCHIC", "GYRO_BALL", "EARTHQUAKE", "CALM_MIND"),
                           M("PSYCHIC", "SHADOW_BALL", "QUICK_ATTACK", "SIGNAL_BEAM"),
                           M("PSYCHIC", "ENERGY_BALL", "FOCUS_BLAST", "RECOVER"),
                           M("DRAIN_PUNCH", "PSYCHO_CUT", "LEAF_BLADE", "STONE_EDGE")],
    "champion_cynthia": [M("SOUL_SIPHON", "DARK_PULSE", "PSYCHIC", "SILVER_WIND"),
                          M("ENERGY_BALL", "SLUDGE_BOMB", "SHADOW_BALL", "TOXIC"),
                          M("AIR_SLASH", "AURA_SPHERE", "WATER_PULSE", "SHOCK_WAVE"),
                          M("AURA_SPHERE", "EXTREME_SPEED", "SHADOW_BALL", "STONE_EDGE"),
                          M("SURF", "ICE_BEAM", "DRAGON_PULSE", "RECOVER"),
                          M("DRAGON_CLAW", "EARTHQUAKE", "FIRE_FANG", "CRUNCH")],
}

# Postgame rematch sets (species fixed by the locked spec; moves = reviewed legal thematic pools, stronger than main story).
CURATED.update({
    "leader_roark_rematch": [M("STONE_EDGE", "AERIAL_ACE", "EARTHQUAKE", "ROCK_SLIDE"),
                              M("WATERFALL", "STONE_EDGE", "SUPERPOWER", "AQUA_TAIL"),
                              M("SURF", "POWER_GEM", "ICE_BEAM", "HYDRO_PUMP"),
                              M("EARTHQUAKE", "STONE_EDGE", "SUPERPOWER", "ROCK_SLIDE"),
                              M("HEAD_SMASH", "EARTHQUAKE", "ZEN_HEADBUTT", "STONE_EDGE")],
    "leader_gardenia_rematch": [M("SEED_BOMB", "ENERGY_BALL", "U_TURN", "SUNNY_DAY"),
                                 M("HYDRO_PUMP", "ENERGY_BALL", "ICE_BEAM", "RAIN_DANCE"),
                                 M("SEED_BOMB", "SKY_UPPERCUT", "SUPERPOWER", "SPORE"),
                                 M("SOLAR_BEAM", "ENERGY_BALL", "SUNNY_DAY", "LEECH_SEED"),
                                 M("SLUDGE_BOMB", "ENERGY_BALL", "SHADOW_BALL", "GIGA_DRAIN")],
    "leader_maylene_rematch": [M("CLOSE_COMBAT", "EARTHQUAKE", "BRICK_BREAK", "REVENGE"),
                                M("BRICK_BREAK", "ZEN_HEADBUTT", "POISON_JAB", "DRAIN_PUNCH"),
                                M("CLOSE_COMBAT", "STONE_EDGE", "NIGHT_SLASH", "AERIAL_ACE"),
                                M("GUNK_SHOT", "BRICK_BREAK", "EARTHQUAKE", "POISON_JAB"),
                                M("CLOSE_COMBAT", "EXTREME_SPEED", "DRAGON_PULSE", "FLASH_CANNON")],
    "leader_wake_rematch": [M("WATERFALL", "DRAGON_PULSE", "IRON_HEAD", "HYDRO_PUMP"),
                             M("AQUA_TAIL", "EARTHQUAKE", "WATERFALL", "ICE_FANG"),
                             M("EARTHQUAKE", "AQUA_TAIL", "STONE_EDGE", "YAWN"),
                             M("EARTHQUAKE", "AQUA_TAIL", "SUPERPOWER", "ICE_PUNCH"),
                             M("AQUA_JET", "CRUNCH", "ICE_FANG", "WATERFALL")],
    "leader_fantina_rematch": [M("SHADOW_BALL", "SLUDGE_BOMB", "THUNDERBOLT", "OMINOUS_WIND"),
                                M("SHADOW_CLAW", "SUCKER_PUNCH", "THUNDERBOLT", "WILL_O_WISP"),
                                M("SOUL_SIPHON", "DARK_PULSE", "PSYCHIC", "SUCKER_PUNCH"),
                                M("SHADOW_PUNCH", "EARTHQUAKE", "ROCK_SLIDE", "PROTECT"),
                                M("SHADOW_BALL", "THUNDERBOLT", "OMINOUS_WIND", "PSYCHIC")],
    "leader_byron_rematch": [M("THUNDERBOLT", "FLASH_CANNON", "TRI_ATTACK", "THUNDER_WAVE"),
                              M("EARTHQUAKE", "IRON_HEAD", "ROCK_SLIDE", "ICE_FANG"),
                              M("IRON_HEAD", "X_SCISSOR", "NIGHT_SLASH", "SUPERPOWER"),
                              M("FLASH_CANNON", "POWER_GEM", "THUNDERBOLT", "MAGNET_VOLLEY"),
                              M("METAL_BURST", "STONE_EDGE", "EARTHQUAKE", "IRON_DEFENSE")],
    "leader_candice_rematch": [M("ICE_PUNCH", "NIGHT_SLASH", "AVALANCHE", "AERIAL_ACE"),
                                M("EARTHQUAKE", "ICE_FANG", "AVALANCHE", "STONE_EDGE"),
                                M("FROST_RUSH", "IRON_HEAD", "EARTHQUAKE", "ICE_FANG"),
                                M("WOOD_HAMMER", "AVALANCHE", "EARTHQUAKE", "FOCUS_BLAST"),
                                M("BLIZZARD", "SHADOW_BALL", "PSYCHIC", "OMINOUS_WIND")],
    "leader_volkner_rematch": [M("SURF", "DISCHARGE", "ICE_BEAM", "SIGNAL_BEAM"),
                                M("THUNDERBOLT", "SHADOW_BALL", "QUICK_ATTACK", "THUNDER_WAVE"),
                                M("THUNDERBOLT", "METAL_RAY", "FOCUS_BLAST", "SIGNAL_BEAM"),
                                M("THUNDER_FANG", "CRUNCH", "SUPERPOWER", "DISCHARGE"),
                                M("STATIC_STRIKE", "BRICK_BREAK", "ICE_PUNCH", "FIRE_PUNCH")],
    "elite_four_aaron_rematch": [M("AIR_SLASH", "SIGNAL_BEAM", "U_TURN", "DOUBLE_TEAM"),
                                  M("IRON_HEAD", "X_SCISSOR", "NIGHT_SLASH", "QUICK_ATTACK"),
                                  M("CLOSE_COMBAT", "STONE_EDGE", "NIGHT_SLASH", "AERIAL_ACE"),
                                  M("X_SCISSOR", "CLOSE_COMBAT", "EARTHQUAKE", "STONE_EDGE"),
                                  M("ATTACK_ORDER", "AIR_SLASH", "DEFEND_ORDER", "HEAL_ORDER")],
    "elite_four_bertha_rematch": [M("EARTH_POWER", "AQUA_TAIL", "ZEN_HEADBUTT", "SANDSTORM"),
                                   M("EARTHQUAKE", "STONE_EDGE", "CRUNCH", "YAWN"),
                                   M("EARTHQUAKE", "FIRE_PUNCH", "THUNDER_PUNCH", "STONE_EDGE"),
                                   M("EARTHQUAKE", "ICE_FANG", "FIRE_FANG", "THUNDER_FANG"),
                                   M("EARTHQUAKE", "STONE_EDGE", "AVALANCHE", "SUPERPOWER")],
    "elite_four_flint_rematch": [M("FLAMETHROWER", "SLUDGE_BOMB", "DARK_PULSE", "SUNNY_DAY"),
                                  M("FLARE_BLITZ", "CRUNCH", "EXTREME_SPEED", "FIRE_FANG"),
                                  M("FLARE_BLITZ", "SOLAR_BEAM", "BOUNCE", "SUNNY_DAY"),
                                  M("FLARE_BLITZ", "CLOSE_COMBAT", "EARTHQUAKE", "THUNDER_PUNCH"),
                                  M("FLAMETHROWER", "THUNDERBOLT", "SOLAR_BEAM", "FOCUS_BLAST")],
    "elite_four_lucian_rematch": [M("SURF", "PSYCHIC", "ICE_BEAM", "SLACK_OFF"),
                                   M("PSYCHIC", "GYRO_BALL", "EARTHQUAKE", "CALM_MIND"),
                                   M("PSYCHIC", "SHADOW_BALL", "QUICK_ATTACK", "SIGNAL_BEAM"),
                                   M("PSYCHIC", "ENERGY_BALL", "FOCUS_BLAST", "RECOVER"),
                                   M("DRAIN_PUNCH", "PSYCHO_CUT", "LEAF_BLADE", "STONE_EDGE")],
    "champion_cynthia_rematch": [M("SOUL_SIPHON", "DARK_PULSE", "PSYCHIC", "OMINOUS_WIND"),
                                  M("ENERGY_BALL", "SLUDGE_BOMB", "SHADOW_BALL", "GIGA_DRAIN"),
                                  M("AIR_SLASH", "AURA_SPHERE", "WATER_PULSE", "PSYCHIC"),
                                  M("AURA_SPHERE", "DRAGON_PULSE", "PSYCHIC", "EARTHQUAKE"),
                                  M("SURF", "ICE_BEAM", "DRAGON_PULSE", "AQUA_RING"),
                                  M("DRAGON_CLAW", "EARTHQUAKE", "FIRE_FANG", "CRUNCH")],
})
