#ifndef POKEPLATINUM_CONSTANTS_FIELD_AREA_LIGHT_H
#define POKEPLATINUM_CONSTANTS_FIELD_AREA_LIGHT_H

enum AreaLightArchiveID {
    AREA_LIGHT_SET_RETAIL_0 = 0,
    AREA_LIGHT_SET_RETAIL_1,
    AREA_LIGHT_SET_RETAIL_2,
    AREA_LIGHT_SET_RETAIL_3,
    AREA_LIGHT_SET_DEEP_FOREST,
    AREA_LIGHT_SET_SNOW,
    AREA_LIGHT_SET_GALACTIC,
    AREA_LIGHT_SET_MT_CORONET,
    AREA_LIGHT_SET_SPEAR_PILLAR,
    AREA_LIGHT_SET_DISTORTION_WORLD,
    AREA_LIGHT_SET_COUNT,
};

#endif // POKEPLATINUM_CONSTANTS_FIELD_AREA_LIGHT_H
