#!/usr/bin/env python3
"""Implementation queue rebuilt from the mined DS OPPORTUNITY_POOL (phase ds_only).

Ranked items are (a) pool libraries (families of recurring opportunities, ranked by library score) and (b) explicit findings
(ranked by the same ten-dimension composite). Whole-asset replacement libraries compete on the same scale and carry novelty 1 /
low library value, so they do not outrank component/technique/novel work by default. reference_only/reject are never queued.
Unranked: runtime-QA gates for replacement work, ledger needs_evidence items and the pool's needs-evidence queue (clustered).
No Platinum resource is modified; GBA/GBC findings are excluded (PHASE_SCOPE.json).
"""
from __future__ import annotations

import collections

from common import *  # noqa: F401,F403
import mine_pool
import opportunities as opp
import outcomes


def derive(pool: dict | None = None) -> dict:
    subs = jload(SUBSYSTEMS_JSON)["subsystems"]
    done = sorted(n for n in subs if (SEL / "ledgers" / f"{n}.json").is_file())
    pending = [{"subsystem": n} for n in sorted(subs) if n not in done]
    ds = set(opp.scope()["ds_sources"])
    pool = pool or jload(mine_pool.POOL_JSON)  # the committed pool (run mine_pool.py first); never re-mines
    ne = jload(mine_pool.NE_JSON)["items"]
    items: list[dict] = []
    for l in pool["libraries"]:
        if l["promoted"] == 0 or l["promoted"] / l["records"] < 0.5:  # mostly-unverified libraries wait in the needs-evidence clusters
            continue
        items.append({"kind": "library", "opportunity_class": l["classification"], "use_mode": l["use_mode"], "title": f"{l['family']} [{l['source_id']}/{l['domain']}] {l['classification']}", "subsystem": l["domain"], "source_id": l["source_id"],
                      "records": l["records"], "promoted": l["promoted"], "needs_evidence": l["needs_evidence"], "members": l["members"], "rank_score": l["score"], "host": l["host"]["system"],
                      "components": list(l["components"])[:4], "techniques": list(l["techniques"])[:4], "top_records": l["top_records"][:3], "library_id": l["library_id"]})
    for r in pool["records"]:
        if r["origin"] == "explicit" and r.get("composite"):
            items.append({"kind": "explicit", "opportunity_class": r["classification"], "use_mode": r["use_mode"], "title": r["title"], "subsystem": r["subsystem"], "source_id": r["source_id"],
                          "records": 1, "promoted": 1, "needs_evidence": 0, "members": len(r.get("group_ids", [])), "rank_score": r["composite"], "host": r["platinum_host"]["system"],
                          "components": r["component_categories"][:4], "techniques": [], "top_records": [r["opportunity_id"]], "finding_id": r["opportunity_id"]})
    assert all(i["source_id"].split(",")[0] in ds for i in items), "non-DS donor leaked into the queue"
    tier = {k: v["tier"] for k, v in opp.taxonomy()["classes"].items()}
    items.sort(key=lambda i: (-i["rank_score"], tier[i["opportunity_class"]], i["title"]))
    for n, it in enumerate(items, 1):
        it["rank"] = n
    clusters = collections.defaultdict(lambda: {"records": 0, "best": 0.0, "next": ""})
    for e in ne:
        c = clusters[(e["source_id"], e["domain"], e["family"], e["classification"])]
        c["records"] += 1
        c["best"] = max(c["best"], e["composite"])
        c["next"] = e["next_evidence"]
    unranked = [{"kind": "needs_evidence_cluster", "source_id": k[0], "domain": k[1], "family": k[2], "opportunity_class": k[3], "records": v["records"], "best_composite": v["best"], "next_evidence": v["next"]}
                for k, v in sorted(clusters.items(), key=lambda kv: (-kv[1]["best"], kv[0]))]
    gates = []
    for sname in done:
        for d in jload(SEL / "ledgers" / f"{sname}.json")["decisions"]:
            if d["role"] == "preferred" and d["needs_runtime_validation"]:
                gates.append((sname, d["source_id"]))
    for (sname, src), n in sorted(collections.Counter(gates).items()):
        unranked.append({"kind": "runtime_qa_gate", "source_id": src, "domain": sname, "opportunity_class": "replacement_candidate", "records": n, "next_evidence": "runtime QA before any replacement import"})
    return {"schema_version": 4, "phase": "ds_only",
            "inputs": {"pool_sha256": file_sha256(mine_pool.POOL_JSON) if mine_pool.POOL_JSON.is_file() else None, "scope_sha256": file_sha256(opp.SCOPE_JSON), "classes_sha256": file_sha256(opp.CLASSES_JSON)},
            "completed_subsystems": done, "pending_subsystems": pending, "ranked": items, "unranked": unranked}


def write_md(q: dict) -> None:
    L = ["# Donor Implementation Queue", "", "Generated by `build_queue.py` from `OPPORTUNITY_POOL.json`. Phase: **DS-only** (GBA/GBC findings deferred). Ranked across all eight classes by opportunity score (ten dimensions, 1-5); libraries are families of recurring opportunities. reference_only/reject are never queued. No Platinum resource is modified.", "",
         f"- ranked items: {len(q['ranked'])}; unranked evidence/QA clusters: {len(q['unranked'])}", "", "## Ranked (top 40)", "",
         "| # | Class | Item | Use | Source | Records (promoted/needs-ev) | Score |", "|---:|---|---|---|---|---|---:|"]
    for i in q["ranked"][:40]:
        L.append(f"| {i['rank']} | {i['opportunity_class']} | {i['title'][:78]} | {i['use_mode']} | {i['source_id']} | {i['records']} ({i['promoted']}/{i['needs_evidence']}) | {i['rank_score']} |")
    by = collections.Counter(i["opportunity_class"] for i in q["ranked"])
    L += ["", "Ranked items by class: " + ", ".join(f"{k} {v}" for k, v in by.most_common()), "", "## Unranked: needs-evidence clusters and QA gates (top 25)", "", "| Kind | Class | Source | Domain/family | Records | Next evidence |", "|---|---|---|---|---:|---|"]
    for u in q["unranked"][:25]:
        L.append(f"| {u['kind']} | {u['opportunity_class']} | {u['source_id']} | {u['domain']}{'/' + u['family'] if u.get('family') else ''} | {u['records']} | {u['next_evidence'][:70]} |")
    (SEL / "IMPLEMENTATION_QUEUE.md").write_text("\n".join(L) + "\n")


def main() -> int:
    q = derive(None)
    jdump(SEL / "IMPLEMENTATION_QUEUE.json", q)
    write_md(q)
    print(f"queue: {len(q['ranked'])} ranked, {len(q['unranked'])} unranked")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
