#!/usr/bin/env python3
"""OUTCOME_STATUS.json/.md: derived replacement outcomes + explicit component/composite/technique use records."""
from __future__ import annotations

from common import *  # noqa: F401,F403
import outcomes


def ledgers() -> dict:
    return {p.stem: jload(p) for p in sorted((SEL / "ledgers").glob("*.json"))}


def derive() -> dict:
    return outcomes.derive_status(jload(GROUPS_JSON)["groups"], ledgers())


def main() -> int:
    d = derive()
    jdump(SEL / "OUTCOME_STATUS.json", d)
    cols = list(outcomes.vocab()["outcomes"])
    L = ["# Donor Use Outcomes", "", "Generated by `build_outcomes.py`. Replacement outcomes are derived from the ledgers (unchanged); component/composite/technique use records are explicit (`components/*.json`). No Platinum resource is modified.", "",
         "| Subsystem | " + " | ".join(cols) + " | confirmed | composites | no-component reviews |", "|---|" + "---:|" * (len(cols) + 3)]
    for r in d["subsystems"]:
        cells = []
        for c in cols:
            n = r["replacement_outcomes"].get(c, 0) + r["use_records"].get(c, 0)
            cells.append(str(n) if n else "-")
        L.append(f"| {r['subsystem']} | " + " | ".join(cells) + f" | {r['records_human_confirmed'] or '-'} | {sum(r['composites'].values()) or '-'} | {r['component_reviews'] or '-'} |")
    L += ["", "Replacement-axis columns count groups (derived); component_donor / composite_input count explicit records; technique_reference is the derived technique-class pool plus explicit records."]
    (SEL / "OUTCOME_STATUS.md").write_text("\n".join(L) + "\n")
    print("\n".join(L[4:-2]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
