#!/usr/bin/env python3
"""SELECTION_STATUS.json/.md: per-subsystem state (pending/selected), role counts, blockers."""
from __future__ import annotations

from common import *  # noqa: F401,F403


def derive() -> dict:
    subs = jload(SUBSYSTEMS_JSON)["subsystems"]
    gdoc = jload(GROUPS_JSON)
    rows = []
    for name in sorted(subs):
        gs = [g for g in gdoc["groups"] if g["subsystem"] == name]
        lp = SEL / "ledgers" / f"{name}.json"
        row = {"subsystem": name, "groups": len(gs), "members": sum(g["member_count"] for g in gs),
               "targets": len({g["target_id"] for g in gs}), "state": "pending"}
        if lp.is_file():
            led = jload(lp)
            row.update({"state": "selected", "roles": led["summary"]["roles"], "target_resolution": led["summary"]["target_resolution"],
                        "needs_evidence": led["summary"]["needs_evidence"]})
        rows.append(row)
    return {"schema_version": 1, "candidate_group_totals": gdoc["totals"], "subsystems": rows}


def main() -> int:
    d = derive()
    jdump(SEL / "SELECTION_STATUS.json", d)
    L = ["# Donor Selection Status", "", "Generated by `build_status.py`. No Platinum resource is modified.", "",
         "| Subsystem | State | Groups | Targets | preferred | alternate | reference_only | not_selected | needs_evidence |", "|---|---|---:|---:|---:|---:|---:|---:|---:|"]
    for r in d["subsystems"]:
        ro = r.get("roles", {})
        L.append(f"| {r['subsystem']} | {r['state']} | {r['groups']} | {r['targets']} | {ro.get('preferred', '-')} | {ro.get('alternate', '-')} | {ro.get('reference_only', '-')} | {ro.get('not_selected', '-')} | {r.get('needs_evidence', '-')} |")
    (SEL / "SELECTION_STATUS.md").write_text("\n".join(L) + "\n")
    print("\n".join(L[4:]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
