#!/usr/bin/env python3
"""OPPORTUNITY_REGISTER.json/.md: unified canonical-class register (explicit findings + existing use records + ledger verdicts)."""
from __future__ import annotations

from common import *  # noqa: F401,F403
import opportunities as opp
import json
import outcomes


def ledgers() -> dict:
    return {p.stem: jload(p) for p in sorted((SEL / "ledgers").glob("*.json"))}


def derive() -> dict:
    return opp.derive_register(ledgers(), outcomes.load_use_files())


def main() -> int:
    d = derive()
    jdump(SEL / "OPPORTUNITY_REGISTER.json", d)
    tx = opp.taxonomy()
    L = ["# Donor Opportunity Register", "", "Generated by `build_opportunities.py`. Canonical classes: `OPPORTUNITY_CLASSES.json`. Explicit findings: `opportunities/findings.json`. No Platinum resource is modified.", "",
         "| Class | Tier | Findings/records |", "|---|---:|---:|"]
    for c in tx["implementation_order"] + ["reference_only", "reject"]:
        L.append(f"| {c} | {tx['classes'][c]['tier']} | {d['counts_by_class'][c]} |")
    L += ["", "Unscoped pools (group-level, not findings; need a Platinum target/system before use): " + ", ".join(f"{k}={v}" for k, v in d["unscoped_pools"].items()), "",
          f"Needs donor verification ({len(d['needs_donor_verification'])}): evidence not recorded in this repo.", "",
          "| Class | Id | Origin | Subsystem/host | Source | Feas. | Verified |", "|---|---|---|---|---|---:|---|"]
    for r in d["rows"]:
        L.append(f"| {r['classification']} | {r['id']} | {r['origin']} | {r['subsystem']} | {r['source_id']} | {r.get('feasibility') or '-'} | {'yes' if r['verified'] else 'NO'} |")
    (SEL / "OPPORTUNITY_REGISTER.md").write_text("\n".join(L) + "\n")
    print(json.dumps(d["counts_by_class"]), d["unscoped_pools"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
