#!/usr/bin/env python3
"""Prioritized implementation queue from completed subsystem ledgers (plus open evidence work).

Only subsystems with a ledger participate. Queue items:
  implement  - a preferred donor group (one item per subsystem+source batch), ranked by value/cost
  evidence   - reference_only(needs_evidence) groups whose gain could flip them into selection
  runtime_qa - preferred/alternate groups flagged needs_runtime_validation
Pending subsystems (no ledger yet) are listed so the queue is visibly incomplete, not silently short.
"""
from __future__ import annotations

import argparse
import collections
import sys

from common import *  # noqa: F401,F403


def derive() -> dict:
    subs = jload(SUBSYSTEMS_JSON)["subsystems"]
    gdoc = jload(GROUPS_JSON)
    done, pending = [], []
    implement: dict[tuple, dict] = {}
    evidence: dict[tuple, dict] = {}
    runtime: dict[tuple, dict] = {}
    for name in sorted(subs):
        lp = SEL / "ledgers" / f"{name}.json"
        if not lp.is_file():
            n = sum(1 for g in gdoc["groups"] if g["subsystem"] == name)
            pending.append({"subsystem": name, "groups": n})
            continue
        led = jload(lp)
        done.append(name)
        w = subs[name]["priority_weight"]
        for d in led["decisions"]:
            key = (name, d["source_id"])
            if d["role"] == "preferred":
                it = implement.setdefault(key, {"kind": "implement", "subsystem": name, "source_id": d["source_id"], "targets": [], "gain_sum": 0, "cost": d["scores"]["integration_cost"], "formats": set()})
                it["targets"].append(d["target_id"])
                it["gain_sum"] += d["scores"]["visual_gain"]
                it["formats"].add(d["format_family"])
            if d["role"] in ("preferred", "alternate") and d["needs_runtime_validation"]:
                it = runtime.setdefault(key, {"kind": "runtime_qa", "subsystem": name, "source_id": d["source_id"], "groups": 0})
                it["groups"] += 1
            if d["needs_evidence"]:
                it = evidence.setdefault(key, {"kind": "evidence", "subsystem": name, "source_id": d["source_id"], "groups": 0, "members": 0, "targets": []})
                it["groups"] += 1
                it["members"] += d["asset_identity"]["member_count"]
                it["targets"].append(d["target_id"])
    items = []
    for it in implement.values():
        w = subs[it["subsystem"]]["priority_weight"]
        items.append({
            "kind": "implement", "subsystem": it["subsystem"], "source_id": it["source_id"],
            "target_count": len(it["targets"]), "targets_sample": sorted(it["targets"])[:5],
            "format_families": sorted(it["formats"]), "integration_cost": it["cost"],
            "priority_score": round(it["gain_sum"] * w / max(it["cost"], 1), 3),
        })
    for it in evidence.values():
        items.append({**it, "targets": None, "target_count": len(it["targets"]), "targets_sample": sorted(it["targets"])[:5],
                      "priority_score": round(0.1 * subs[it["subsystem"]]["priority_weight"], 3)})
    for it in runtime.values():
        items.append({**it, "priority_score": 0.0})
    items.sort(key=lambda i: (-i["priority_score"], i["kind"], i["subsystem"], i["source_id"]))
    for n, it in enumerate(items, 1):
        it["rank"] = n
    return {
        "schema_version": 1,
        "inputs": {"ledger_files": {n: file_sha256(SEL / "ledgers" / f"{n}.json") for n in done}},
        "completed_subsystems": done,
        "pending_subsystems": pending,
        "items": items,
    }


def write_md(q: dict) -> None:
    L = ["# Donor Implementation Queue", "", "Generated by `build_queue.py` from completed selection ledgers. No Platinum resource is modified.", ""]
    L.append(f"- completed subsystems: {', '.join(q['completed_subsystems']) or 'none'}")
    L.append(f"- pending subsystems: {len(q['pending_subsystems'])}")
    L.append("")
    if q["items"]:
        L += ["| # | Kind | Subsystem | Source | Targets/groups | Score |", "|---:|---|---|---|---:|---:|"]
        for i in q["items"]:
            n = i.get("target_count", i.get("groups"))
            L.append(f"| {i['rank']} | {i['kind']} | {i['subsystem']} | {i['source_id']} | {n} | {i['priority_score']} |")
    else:
        L.append("_No implementation work is currently justified by completed selections._")
    (SEL / "IMPLEMENTATION_QUEUE.md").write_text("\n".join(L) + "\n")


def main() -> int:
    q = derive()
    jdump(SEL / "IMPLEMENTATION_QUEUE.json", q)
    write_md(q)
    print(f"queue items: {len(q['items'])}; completed: {q['completed_subsystems']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
