name: build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  LM_LICENSE_FILE: "${{ github.workspace }}/tools/cw/license.dat"
  BUILD: /var/tmp/pokeplatinum

jobs:
  build:
    name: build (US rev ${{ matrix.revision }})
    strategy:
      fail-fast: false
      matrix:
        revision: [0, 1]
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - name: Install Software
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends bison flex g++ gcc-arm-none-eabi git make ninja-build pkg-config python3 wget xz-utils

      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Install Metroskrew
        run: sudo make skrew

      - name: Configure Repo
        run: make configure ROM_REVISION=${{ matrix.revision }}

      - name: Build Modded ROM
        run: make rom ROM_REVISION=${{ matrix.revision }}

      - name: Post error archive
        if: failure()
        continue-on-error: true
        run: tar czf failure-rev${{ matrix.revision }}.tar.gz "$BUILD"

      - name: Post error upload
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: pokeplatinum-failure-${{ github.run_id }}-rev${{ matrix.revision }}
          path: failure-rev${{ matrix.revision }}.tar.gz
          retention-days: 1
